M48
; DRILL file {KiCad 7.0.5-4d25ed1034~172~ubuntu22.04.1} date Fri 07 Jul 2023 08:06:02 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-07T08:06:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-4d25ed1034~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X31.74Y-27.41
X31.74Y-33.19
T2
X27.5Y-12.0
X27.5Y-62.0
X122.5Y-12.0
X122.5Y-62.0
T0
M30
